
--1.
CREATE SEQUENCE DIET_ID_GENERATE_SEQUENCE
INCREMENT BY 1
START WITH 101
MAXVALUE 500
NOCACHE
NOCYCLE;

--2.
CREATE OR REPLACE FUNCTION AGE(X IN DATE)
RETURN NUMBER
AS
Today DATE;
Var NUMBER;
	
BEGIN
	Today:=SYSDATE;
        SELECT ROUND((Today-X)/365) INTO Var from dual;
RETURN Var;

END;

--3.
CREATE TABLE FIXED_BY_TRAINER
(
        Trainer varchar2(50),
        Username varchar2(50),
        Diet_Id NUMBER,
        Fixed_Date DATE DEFAULT SYSDATE,
        Fixed_Time TIMESTAMP DEFAULT SYSTIMESTAMP
);

