INSERT INTO EMPLOYEE(
    USERNAME,EMP_ID,SALARY,EXPERIENCE,EDUCATION,DESIGNATION
)VALUES(
    'modasayedul',14,60000,02,'BBA In Marketing','Manager'
);

INSERT INTO EMPLOYEE(
    USERNAME,EMP_ID,SALARY,EXPERIENCE,EDUCATION,DESIGNATION
)VALUES(
    'khaled',15,55000,01,'BSC In CSE','Manager'
);

INSERT INTO EMPLOYEE(
    USERNAME,EMP_ID,SALARY,EXPERIENCE,EDUCATION,DESIGNATION
)VALUES(
    'sowmik',16,50000,01,'BSC In CSE','Manager'
);

INSERT INTO EMPLOYEE(
    USERNAME,EMP_ID,SALARY,SHIFT,EXPERIENCE,EDUCATION,NUM_OF_RATING,RATING_VALUE,DESIGNATION
)VALUES(
    'shafin',17,10000,07,02,'BBA In Physical Studies',3,4.5,'Trainer'
);


INSERT INTO EMPLOYEE(
    USERNAME,EMP_ID,SALARY,SHIFT,EXPERIENCE,EDUCATION,NUM_OF_RATING,RATING_VALUE,DESIGNATION
)VALUES(
    'sakib',18,10000,08,02,'BBA In Physical Studies',1,4,'Trainer'
);


INSERT INTO EMPLOYEE(
    USERNAME,EMP_ID,SALARY,SHIFT,EXPERIENCE,EDUCATION,NUM_OF_RATING,RATING_VALUE,DESIGNATION
)VALUES(
    'adib',19,12000,10,03,'BSC In CSE',1,5,'Trainer'
);

INSERT INTO EMPLOYEE(
    USERNAME,EMP_ID,SALARY,SHIFT,EXPERIENCE,EDUCATION,NUM_OF_RATING,RATING_VALUE,DESIGNATION
)VALUES(
    'nizami',20,13000,10,02,'BSC In CSE',2,5,'Trainer'
);


INSERT INTO EMPLOYEE(
    USERNAME,EMP_ID,SALARY,SHIFT,EXPERIENCE,EDUCATION,NUM_OF_RATING,RATING_VALUE,DESIGNATION
)VALUES(
    'rakib',21,15000,11,04,'BSC In CSE',1,4,'Trainer'
);

INSERT INTO EMPLOYEE(
    USERNAME,EMP_ID,SALARY,SHIFT,EXPERIENCE,EDUCATION,NUM_OF_RATING,RATING_VALUE,DESIGNATION
)VALUES(
    'rafid147',22,20000,02,05,'BBA In Physical Studies',1,5,'Trainer'
);

INSERT INTO EMPLOYEE(
    USERNAME,EMP_ID,SALARY,SHIFT,EXPERIENCE,EDUCATION,NUM_OF_RATING,RATING_VALUE,DESIGNATION
)VALUES(
    'ishraq',23,8000,04,0,'BSC In CSE',1,3.5,'Trainer'
);

INSERT INTO EMPLOYEE(
    USERNAME,EMP_ID,SALARY,SHIFT,EXPERIENCE,EDUCATION,NUM_OF_RATING,RATING_VALUE,DESIGNATION
)VALUES(
    'mahmud',24,9500,06,01,'BSC In CSE',2,4,'Trainer'
);


INSERT INTO EMPLOYEE(
    USERNAME,EMP_ID,SALARY,SHIFT,EXPERIENCE,EDUCATION,NUM_OF_RATING,RATING_VALUE,DESIGNATION
)VALUES(
    'enan',25,11000,08,02,'BSC In CSE',1,4.5,'Trainer'
);


INSERT INTO EMPLOYEE(
    USERNAME,EMP_ID,SALARY,SHIFT,EXPERIENCE,EDUCATION,DESIGNATION
)VALUES(
    'bibhor',26,5000,07,0,'Passed HSC','Receptionist'
);

INSERT INTO EMPLOYEE(
    USERNAME,EMP_ID,SALARY,SHIFT,EXPERIENCE,EDUCATION,DESIGNATION
)VALUES(
    'hasim',27,5000,08,1,'Passed SSC','Receptionist'
);

INSERT INTO EMPLOYEE(
    USERNAME,EMP_ID,SALARY,SHIFT,EXPERIENCE,EDUCATION,DESIGNATION
)VALUES(
    'akash',28,5000,09,1,'Passed SSC','Receptionist'
);

INSERT INTO EMPLOYEE(
    USERNAME,EMP_ID,SALARY,SHIFT,EXPERIENCE,EDUCATION,DESIGNATION
)VALUES(
    'faisal',29,7000,10,2,'Passed HSC','Receptionist'
);

INSERT INTO EMPLOYEE(
    USERNAME,EMP_ID,SALARY,SHIFT,EXPERIENCE,EDUCATION,DESIGNATION
)VALUES(
    'tariq',30,7500,12,2,'Passed SSC','Receptionist'
);


INSERT INTO EMPLOYEE(
    USERNAME,EMP_ID,SALARY,SHIFT,EXPERIENCE,EDUCATION,DESIGNATION
)VALUES(
    'astha',31,8500,02,2,'Passed SSC','Receptionist'
);

INSERT INTO EMPLOYEE(
    USERNAME,EMP_ID,SALARY,SHIFT,EXPERIENCE,EDUCATION,DESIGNATION
)VALUES(
    'mayesha',32,6000,02,2,'Passed SSC','Receptionist'
);

INSERT INTO EMPLOYEE(
    USERNAME,EMP_ID,SALARY,SHIFT,EXPERIENCE,EDUCATION,DESIGNATION
)VALUES(
    'shakira',33,10000,04,3,'Passed SSC','Receptionist'
);

INSERT INTO EMPLOYEE(
    USERNAME,EMP_ID,SALARY,SHIFT,EXPERIENCE,EDUCATION,DESIGNATION
)VALUES(
    'karim',34,6000,06,1,'Passed SSC','Receptionist'
);


INSERT INTO EMPLOYEE(
    USERNAME,EMP_ID,SALARY,SHIFT,EXPERIENCE,EDUCATION,DESIGNATION
)VALUES(
    'harun',35,7000,07,1,'Passed SSC','Receptionist'
);

INSERT INTO EMPLOYEE(
    USERNAME,EMP_ID,SALARY,SHIFT,EXPERIENCE,EDUCATION,DESIGNATION
)VALUES(
    'arnab007',36,7000,08,2,'Passed SSC','Receptionist'
);


