insert into Equipment(EQUIPMENT_AVAILABLE,EQUIPMENT_ID,EQUIPMENT_NAME,
EQUIPMENT_BRAND,EQUIPMENT_MODEL,BR_NAME)values(5,101,'Training Bench','GYM80','G4010 Multi Position','br_001');

insert into Equipment(EQUIPMENT_AVAILABLE,EQUIPMENT_ID,EQUIPMENT_NAME,
EQUIPMENT_BRAND,EQUIPMENT_MODEL,BR_NAME)values(5,102,'Dumbbell Set','GYM770','G408','br_001');

insert into Equipment(EQUIPMENT_AVAILABLE,EQUIPMENT_ID,EQUIPMENT_NAME,
EQUIPMENT_BRAND,EQUIPMENT_MODEL,BR_NAME)values(5,103,'Treadmill','GYM980','G509','br_001');

insert into Equipment(EQUIPMENT_AVAILABLE,EQUIPMENT_ID,EQUIPMENT_NAME,
EQUIPMENT_BRAND,EQUIPMENT_MODEL,BR_NAME)values(5,104,'Stationary Bicycle','GYM380','G309','br_001');

insert into Equipment(EQUIPMENT_AVAILABLE,EQUIPMENT_ID,EQUIPMENT_NAME,
EQUIPMENT_BRAND,EQUIPMENT_MODEL,BR_NAME)values(5,105,'Rowing Machine','GYM780','G707','br_001');



insert into Equipment(EQUIPMENT_AVAILABLE,EQUIPMENT_ID,EQUIPMENT_NAME,
EQUIPMENT_BRAND,EQUIPMENT_MODEL,BR_NAME)values(5,201,'Training Bench','GYM80','G4010 Multi Position','br_002');

insert into Equipment(EQUIPMENT_AVAILABLE,EQUIPMENT_ID,EQUIPMENT_NAME,
EQUIPMENT_BRAND,EQUIPMENT_MODEL,BR_NAME)values(5,202,'Dumbbell Set','GYM770','G408','br_002');

insert into Equipment(EQUIPMENT_AVAILABLE,EQUIPMENT_ID,EQUIPMENT_NAME,
EQUIPMENT_BRAND,EQUIPMENT_MODEL,BR_NAME)values(5,203,'Treadmill','GYM980','G509','br_002');

insert into Equipment(EQUIPMENT_AVAILABLE,EQUIPMENT_ID,EQUIPMENT_NAME,
EQUIPMENT_BRAND,EQUIPMENT_MODEL,BR_NAME)values(5,204,'Stationary Bicycle','GYM380','G309','br_002');

insert into Equipment(EQUIPMENT_AVAILABLE,EQUIPMENT_ID,EQUIPMENT_NAME,
EQUIPMENT_BRAND,EQUIPMENT_MODEL,BR_NAME)values(5,205,'Rowing Machine','GYM780','G707','br_002');



insert into Equipment(EQUIPMENT_AVAILABLE,EQUIPMENT_ID,EQUIPMENT_NAME,
EQUIPMENT_BRAND,EQUIPMENT_MODEL,BR_NAME)values(5,301,'Training Bench','GYM80','G4010 Multi Position','br_003');

insert into Equipment(EQUIPMENT_AVAILABLE,EQUIPMENT_ID,EQUIPMENT_NAME,
EQUIPMENT_BRAND,EQUIPMENT_MODEL,BR_NAME)values(5,302,'Dumbbell Set','GYM770','G408','br_003');

insert into Equipment(EQUIPMENT_AVAILABLE,EQUIPMENT_ID,EQUIPMENT_NAME,
EQUIPMENT_BRAND,EQUIPMENT_MODEL,BR_NAME)values(5,303,'Treadmill','GYM980','G509','br_003');

insert into Equipment(EQUIPMENT_AVAILABLE,EQUIPMENT_ID,EQUIPMENT_NAME,
EQUIPMENT_BRAND,EQUIPMENT_MODEL,BR_NAME)values(5,304,'Stationary Bicycle','GYM380','G309','br_003');

insert into Equipment(EQUIPMENT_AVAILABLE,EQUIPMENT_ID,EQUIPMENT_NAME,
EQUIPMENT_BRAND,EQUIPMENT_MODEL,BR_NAME)values(5,305,'Rowing Machine','GYM780','G707','br_003');





