INSERT INTO EXERCISES_LIST (
  EXE_ID, EXE_NAME, BEG_CAL_BURN_PER_SET, INTER_CAL_BURN_PER_SET, EXP_CAL_BURN_PER_SET, EXE_TYPE, MIN_WEIGHT, 
  BEG_NUM_OF_SET,INTER_NUM_OF_SET,EXP_NUM_OF_SET,MIN_AGE,MIN_HEIGHT,BEG_PER_SET_ITEM,INTER_PER_SET_ITEM,
  EXP_PER_SET_ITEM
)
VALUES(
    'EXE_001','JUMP ROPE',40,60,80,'JUMPING',55,30,40,70,16,150,1,2,2
);

INSERT INTO EXERCISES_LIST (
  EXE_ID, EXE_NAME, BEG_CAL_BURN_PER_SET, INTER_CAL_BURN_PER_SET, EXP_CAL_BURN_PER_SET, EXE_TYPE, MIN_WEIGHT, 
  BEG_NUM_OF_SET,INTER_NUM_OF_SET,EXP_NUM_OF_SET,MIN_AGE,MIN_HEIGHT,BEG_PER_SET_ITEM,INTER_PER_SET_ITEM,
  EXP_PER_SET_ITEM
)
VALUES(
    'EXE_002','PUSH UP',20,30,40,'COMPOUND BODYWEIGHT',60,15,20,30,18,155,1,2,3
);

INSERT INTO EXERCISES_LIST (
  EXE_ID, EXE_NAME, BEG_CAL_BURN_PER_SET, INTER_CAL_BURN_PER_SET, EXP_CAL_BURN_PER_SET, EXE_TYPE, 
  BEG_NUM_OF_SET,INTER_NUM_OF_SET,EXP_NUM_OF_SET,BEG_PER_SET_ITEM,INTER_PER_SET_ITEM,
  EXP_PER_SET_ITEM
)
VALUES(
    'EXE_003','SQUATS',10,15,25,'DYNAMIC STRENGTH TRAINING',15,20,30,1,2,3
);

INSERT INTO EXERCISES_LIST (
  EXE_ID, EXE_NAME, BEG_CAL_BURN_PER_SET, INTER_CAL_BURN_PER_SET, EXP_CAL_BURN_PER_SET, EXE_TYPE, 
  BEG_NUM_OF_SET,INTER_NUM_OF_SET,EXP_NUM_OF_SET,BEG_PER_SET_ITEM,INTER_PER_SET_ITEM,
  EXP_PER_SET_ITEM
)
VALUES(
    'EXE_004','DUMBBELL PRESS',5,10,15,'PRESS MUSCLES',15,20,40,1,2,3
);


INSERT INTO EXERCISES_LIST (
  EXE_ID, EXE_NAME, BEG_CAL_BURN_PER_SET, INTER_CAL_BURN_PER_SET, EXP_CAL_BURN_PER_SET, EXE_TYPE, MIN_WEIGHT, 
  BEG_NUM_OF_SET,INTER_NUM_OF_SET,EXP_NUM_OF_SET,MIN_AGE,MIN_HEIGHT,BEG_PER_SET_ITEM,INTER_PER_SET_ITEM,
  EXP_PER_SET_ITEM
)
VALUES(
    'EXE_005','DUMBBELL ROWS',5,10,15,'COMPOUND BACK',60,15,20,30,18,155,1,2,3
);

INSERT INTO EXERCISES_LIST (
  EXE_ID, EXE_NAME, BEG_CAL_BURN_PER_SET, INTER_CAL_BURN_PER_SET, EXP_CAL_BURN_PER_SET, EXE_TYPE, 
  BEG_NUM_OF_SET,INTER_NUM_OF_SET,EXP_NUM_OF_SET,BEG_PER_SET_ITEM,INTER_PER_SET_ITEM,
  EXP_PER_SET_ITEM
)
VALUES(
    'EXE_006','SINGLE-LEG DEADLIFTS',5,10,15,'HIP HINGE MOVEMENT',15,30,35,1,1,1
);


INSERT INTO EXERCISES_LIST (
  EXE_ID, EXE_NAME, BEG_CAL_BURN_PER_SET, INTER_CAL_BURN_PER_SET, EXP_CAL_BURN_PER_SET, EXE_TYPE, 
  BEG_NUM_OF_SET,INTER_NUM_OF_SET,EXP_NUM_OF_SET,BEG_PER_SET_ITEM,INTER_PER_SET_ITEM,
  EXP_PER_SET_ITEM
)
VALUES(
    'EXE_007','BURPEES',5,5,5,'CALISTHENICS',10,10,10,1,1,1
);

INSERT INTO EXERCISES_LIST (
  EXE_ID, EXE_NAME, INTER_CAL_BURN_PER_SET, EXP_CAL_BURN_PER_SET, EXE_TYPE, MIN_WEIGHT, 
  INTER_NUM_OF_SET,EXP_NUM_OF_SET,MIN_AGE,INTER_PER_SET_ITEM,
  EXP_PER_SET_ITEM
)
VALUES(
    'EXE_008','DEADLIFT',45,50,'COMPOUND EXERCISE',70,25,30,22,2,2
);

INSERT INTO EXERCISES_LIST (
  EXE_ID, EXE_NAME, INTER_CAL_BURN_PER_SET, EXP_CAL_BURN_PER_SET, EXE_TYPE, MIN_WEIGHT, 
  INTER_NUM_OF_SET,EXP_NUM_OF_SET,MIN_AGE,INTER_PER_SET_ITEM,
  EXP_PER_SET_ITEM
)
VALUES(
    'EXE_009','PULL UPS',60,80,'BACK STRENGTHENING',65,15,20,20,2,2
);

INSERT INTO EXERCISES_LIST (
  EXE_ID, EXE_NAME, BEG_CAL_BURN_PER_SET,  EXE_TYPE,  
  BEG_NUM_OF_SET,MIN_AGE,BEG_PER_SET_ITEM
)
VALUES(
    'EXE_010','LEG CURL',15,'HAMSTRING STRENGTHENING',30,18,2
);