INSERT INTO EXERCISES_LIST (
  EXE_ID, EXE_NAME, BEG_CAL_BURN_PER_SET, INTER_CAL_BURN_PER_SET, EXP_CAL_BURN_PER_SET, EXE_TYPE, MIN_WEIGHT, 
  BEG_NUM_OF_SET,INTER_NUM_OF_SET,EXP_NUM_OF_SET,MIN_AGE,MIN_HEIGHT,BEG_PER_SET_ITEM,INTER_PER_SET_ITEM,
  EXP_PER_SET_ITEM
)
VALUES(
    2001,'JUMP ROPE',40,60,80,'JUMPING',55,30,40,70,16,150,1,2,2
);

INSERT INTO EXERCISES_LIST (
  EXE_ID, EXE_NAME, BEG_CAL_BURN_PER_SET, INTER_CAL_BURN_PER_SET, EXP_CAL_BURN_PER_SET, EXE_TYPE, MIN_WEIGHT, 
  BEG_NUM_OF_SET,INTER_NUM_OF_SET,EXP_NUM_OF_SET,MIN_AGE,MIN_HEIGHT,BEG_PER_SET_ITEM,INTER_PER_SET_ITEM,
  EXP_PER_SET_ITEM
)
VALUES(
    2002,'PUSH UP',20,30,40,'COMPOUND BODYWEIGHT',60,15,20,30,18,155,1,2,3
);

INSERT INTO EXERCISES_LIST (
  EXE_ID, EXE_NAME, BEG_CAL_BURN_PER_SET, INTER_CAL_BURN_PER_SET, EXP_CAL_BURN_PER_SET, EXE_TYPE, 
  BEG_NUM_OF_SET,INTER_NUM_OF_SET,EXP_NUM_OF_SET,BEG_PER_SET_ITEM,INTER_PER_SET_ITEM,
  EXP_PER_SET_ITEM
)
VALUES(
    2003,'SQUATS',10,15,25,'DYNAMIC STRENGTH TRAINING',15,20,30,1,2,3
);

INSERT INTO EXERCISES_LIST (
  EXE_ID, EXE_NAME, BEG_CAL_BURN_PER_SET, INTER_CAL_BURN_PER_SET, EXP_CAL_BURN_PER_SET, EXE_TYPE, 
  BEG_NUM_OF_SET,INTER_NUM_OF_SET,EXP_NUM_OF_SET,BEG_PER_SET_ITEM,INTER_PER_SET_ITEM,
  EXP_PER_SET_ITEM
)
VALUES(
    2004,'DUMBBELL PRESS',5,10,15,'PRESS MUSCLES',15,20,40,1,2,3
);


INSERT INTO EXERCISES_LIST (
  EXE_ID, EXE_NAME, BEG_CAL_BURN_PER_SET, INTER_CAL_BURN_PER_SET, EXP_CAL_BURN_PER_SET, EXE_TYPE, MIN_WEIGHT, 
  BEG_NUM_OF_SET,INTER_NUM_OF_SET,EXP_NUM_OF_SET,MIN_AGE,MIN_HEIGHT,BEG_PER_SET_ITEM,INTER_PER_SET_ITEM,
  EXP_PER_SET_ITEM
)
VALUES(
    2005,'DUMBBELL ROWS',5,10,15,'COMPOUND BACK',60,15,20,30,18,155,1,2,3
);

INSERT INTO EXERCISES_LIST (
  EXE_ID, EXE_NAME, BEG_CAL_BURN_PER_SET, INTER_CAL_BURN_PER_SET, EXP_CAL_BURN_PER_SET, EXE_TYPE, 
  BEG_NUM_OF_SET,INTER_NUM_OF_SET,EXP_NUM_OF_SET,BEG_PER_SET_ITEM,INTER_PER_SET_ITEM,
  EXP_PER_SET_ITEM
)
VALUES(
    2006,'SINGLE-LEG DEADLIFTS',5,10,15,'HIP HINGE MOVEMENT',15,30,35,1,1,1
);


INSERT INTO EXERCISES_LIST (
  EXE_ID, EXE_NAME, BEG_CAL_BURN_PER_SET, INTER_CAL_BURN_PER_SET, EXP_CAL_BURN_PER_SET, EXE_TYPE, 
  BEG_NUM_OF_SET,INTER_NUM_OF_SET,EXP_NUM_OF_SET,BEG_PER_SET_ITEM,INTER_PER_SET_ITEM,
  EXP_PER_SET_ITEM
)
VALUES(
    2007,'BURPEES',5,5,5,'CALISTHENICS',10,10,10,1,1,1
);

INSERT INTO EXERCISES_LIST (
  EXE_ID, EXE_NAME, INTER_CAL_BURN_PER_SET, EXP_CAL_BURN_PER_SET, EXE_TYPE, MIN_WEIGHT, 
  INTER_NUM_OF_SET,EXP_NUM_OF_SET,MIN_AGE,INTER_PER_SET_ITEM,
  EXP_PER_SET_ITEM
)
VALUES(
    2008,'DEADLIFT',45,50,'COMPOUND EXERCISE',70,25,30,22,2,2
);

INSERT INTO EXERCISES_LIST (
  EXE_ID, EXE_NAME, INTER_CAL_BURN_PER_SET, EXP_CAL_BURN_PER_SET, EXE_TYPE, MIN_WEIGHT, 
  INTER_NUM_OF_SET,EXP_NUM_OF_SET,MIN_AGE,INTER_PER_SET_ITEM,
  EXP_PER_SET_ITEM
)
VALUES(
    2009,'PULL UPS',60,80,'BACK STRENGTHENING',65,15,20,20,2,2
);

INSERT INTO EXERCISES_LIST (
  EXE_ID, EXE_NAME, BEG_CAL_BURN_PER_SET,  EXE_TYPE,  
  BEG_NUM_OF_SET,MIN_AGE,BEG_PER_SET_ITEM
)
VALUES(
    2010,'LEG CURL',15,'HAMSTRING STRENGTHENING',30,18,2
);

INSERT INTO EXERCISES_LIST (
  EXE_ID, EXE_NAME, BEG_CAL_BURN_PER_SET,  EXE_TYPE,  
  BEG_NUM_OF_SET,MIN_AGE,BEG_PER_SET_ITEM
)
VALUES(
    2011,'BURPEES',20,'CALISTHENICS',20,22,2
);

INSERT INTO EXERCISES_LIST (
  EXE_ID, EXE_NAME, BEG_CAL_BURN_PER_SET, INTER_CAL_BURN_PER_SET, EXP_CAL_BURN_PER_SET, EXE_TYPE, MIN_WEIGHT, 
  BEG_NUM_OF_SET,INTER_NUM_OF_SET,EXP_NUM_OF_SET,MIN_AGE,MIN_HEIGHT,BEG_PER_SET_ITEM,INTER_PER_SET_ITEM,
  EXP_PER_SET_ITEM
)
VALUES(
    2012,'LUNGES',5,10,15,'LOWER BODY UNILATERAL',60,15,20,30,18,155,1,2,3
);

INSERT INTO EXERCISES_LIST (
  EXE_ID, EXE_NAME, BEG_CAL_BURN_PER_SET, INTER_CAL_BURN_PER_SET, EXP_CAL_BURN_PER_SET, EXE_TYPE, MIN_WEIGHT, 
  BEG_NUM_OF_SET,INTER_NUM_OF_SET,EXP_NUM_OF_SET,MIN_AGE,MIN_HEIGHT,BEG_PER_SET_ITEM,INTER_PER_SET_ITEM,
  EXP_PER_SET_ITEM
)
VALUES(
    2013,'JUMPING JACKS',5,10,15,'SHOULDER AND BACK',60,15,20,30,18,155,1,2,3
);

INSERT INTO EXERCISES_LIST (
  EXE_ID, EXE_NAME, BEG_CAL_BURN_PER_SET, INTER_CAL_BURN_PER_SET, EXP_CAL_BURN_PER_SET, EXE_TYPE, MIN_WEIGHT, 
  BEG_NUM_OF_SET,INTER_NUM_OF_SET,EXP_NUM_OF_SET,MIN_AGE,MIN_HEIGHT,BEG_PER_SET_ITEM,INTER_PER_SET_ITEM,
  EXP_PER_SET_ITEM
)
VALUES(
    2014,'RHOMBOID PULLS',5,10,15,'SHOULDER AND BACK',60,15,20,30,18,155,1,2,3
);

INSERT INTO EXERCISES_LIST (
  EXE_ID, EXE_NAME, BEG_CAL_BURN_PER_SET, INTER_CAL_BURN_PER_SET, EXP_CAL_BURN_PER_SET, EXE_TYPE, MIN_WEIGHT, 
  BEG_NUM_OF_SET,INTER_NUM_OF_SET,EXP_NUM_OF_SET,MIN_AGE,MIN_HEIGHT,BEG_PER_SET_ITEM,INTER_PER_SET_ITEM,
  EXP_PER_SET_ITEM
)
VALUES(
    2015,'ARM SCISSORS',5,10,15,'SHOULDER AND BACK',60,15,20,30,18,155,1,2,3
);

INSERT INTO EXERCISES_LIST (
  EXE_ID, EXE_NAME, BEG_CAL_BURN_PER_SET, INTER_CAL_BURN_PER_SET, EXP_CAL_BURN_PER_SET, EXE_TYPE, MIN_WEIGHT, 
  BEG_NUM_OF_SET,INTER_NUM_OF_SET,EXP_NUM_OF_SET,MIN_AGE,MIN_HEIGHT,BEG_PER_SET_ITEM,INTER_PER_SET_ITEM,
  EXP_PER_SET_ITEM
)
VALUES(
    2016,'COBRA STRETCH',5,10,15,'CHEST INTERMEDIATE',60,15,20,30,18,155,1,2,3
);

INSERT INTO EXERCISES_LIST (
  EXE_ID, EXE_NAME, BEG_CAL_BURN_PER_SET, INTER_CAL_BURN_PER_SET, EXP_CAL_BURN_PER_SET, EXE_TYPE, MIN_WEIGHT, 
  BEG_NUM_OF_SET,INTER_NUM_OF_SET,EXP_NUM_OF_SET,MIN_AGE,MIN_HEIGHT,BEG_PER_SET_ITEM,INTER_PER_SET_ITEM,
  EXP_PER_SET_ITEM
)
VALUES(
    2017,'ARM SCISSORS',5,10,15,'SHOULDER AND BACK',60,15,20,30,18,155,1,2,3
);


INSERT INTO EXERCISES_LIST (
  EXE_ID, EXE_NAME, BEG_CAL_BURN_PER_SET, INTER_CAL_BURN_PER_SET, EXP_CAL_BURN_PER_SET, EXE_TYPE, 
  BEG_NUM_OF_SET,INTER_NUM_OF_SET,EXP_NUM_OF_SET,BEG_PER_SET_ITEM,INTER_PER_SET_ITEM,
  EXP_PER_SET_ITEM
)
VALUES(
    2018,'SIDE LEG CIRCLES LEFT',5,5,5,'LEG ADVANCED',10,10,10,1,1,1
);

INSERT INTO EXERCISES_LIST (
  EXE_ID, EXE_NAME, BEG_CAL_BURN_PER_SET, INTER_CAL_BURN_PER_SET, EXP_CAL_BURN_PER_SET, EXE_TYPE, 
  BEG_NUM_OF_SET,INTER_NUM_OF_SET,EXP_NUM_OF_SET,BEG_PER_SET_ITEM,INTER_PER_SET_ITEM,
  EXP_PER_SET_ITEM
)
VALUES(
    2019,'FLOOR TRICEP DIPS',5,5,5,'ARM ADVANCED',10,10,10,1,1,1
);

INSERT INTO EXERCISES_LIST (
  EXE_ID, EXE_NAME, BEG_CAL_BURN_PER_SET, INTER_CAL_BURN_PER_SET, EXP_CAL_BURN_PER_SET, EXE_TYPE, 
  BEG_NUM_OF_SET,INTER_NUM_OF_SET,EXP_NUM_OF_SET,BEG_PER_SET_ITEM,INTER_PER_SET_ITEM,
  EXP_PER_SET_ITEM
)
VALUES(
    2020,'ALTERNATING HOOKS',5,5,5,'ARM ADVANCED',10,10,10,1,1,1
);