INSERT INTO MEMBER (
  USERNAME, MEM_ID, MEM_HEIGHT, MEM_WEIGHT, MEMBERSHIP_EXPIRY, EXPECTED_OUTCOME, TRAINER
)
  VALUES (
  'afk999', 'M_001', 161, 59,TO_DATE('07/07/2022','dd/mm/yyyy'), 'Reduce Weight','Mushfique Hossain Shafin'
);

INSERT INTO MEMBER (
  USERNAME, MEM_ID, MEM_HEIGHT, MEM_WEIGHT, MEMBERSHIP_EXPIRY, EXPECTED_OUTCOME, TRAINER
)
  VALUES (
  'Ayon037', 'M_002', 165, 75,TO_DATE('20/08/2022','dd/mm/yyyy'), 'Increase Muscle','Farhan Nasif Nizami'
);

INSERT INTO MEMBER (
  USERNAME, MEM_ID, MEM_HEIGHT, MEM_WEIGHT, MEMBERSHIP_EXPIRY, EXPECTED_OUTCOME, TRAINER
)
  VALUES (
  'hasnat', 'M_003', 162, 75,TO_DATE('20/08/2022','dd/mm/yyyy'), 'Reduce Weight','Enan Abdullah Khan'
);

INSERT INTO MEMBER (
  USERNAME, MEM_ID, MEM_HEIGHT, MEM_WEIGHT, MEMBERSHIP_EXPIRY, EXPECTED_OUTCOME, TRAINER
)
  VALUES (
  'rashid', 'M_004', 160, 90,TO_DATE('12/09/2022','dd/mm/yyyy'), 'Reduce Weight','Adib Hossain'
);

INSERT INTO MEMBER (
  USERNAME, MEM_ID, MEM_HEIGHT, MEM_WEIGHT, MEMBERSHIP_EXPIRY, EXPECTED_OUTCOME, TRAINER
)
  VALUES (
  'meher', 'M_005', 164,55,TO_DATE('12/09/2022','dd/mm/yyyy'), 'Increase Weight','Tasnim Ullah Sakib'
);

INSERT INTO MEMBER (
  USERNAME, MEM_ID, MEM_HEIGHT, MEM_WEIGHT, MEMBERSHIP_EXPIRY, EXPECTED_OUTCOME, TRAINER
)
  VALUES (
  'rahat', 'M_006', 167,71,TO_DATE('25/08/2022','dd/mm/yyyy'), 'Reduce Weight','Farhan Nasif Nizami'
);

INSERT INTO MEMBER (
  USERNAME, MEM_ID, MEM_HEIGHT, MEM_WEIGHT, MEMBERSHIP_EXPIRY, EXPECTED_OUTCOME, TRAINER
)
  VALUES (
  'arafat', 'M_007', 168,76,TO_DATE('22/08/2022','dd/mm/yyyy'), 'Reduce Weight','Rakib Hasan'
);

INSERT INTO MEMBER (
  USERNAME, MEM_ID, MEM_HEIGHT, MEM_WEIGHT, MEMBERSHIP_EXPIRY, EXPECTED_OUTCOME, TRAINER
)
  VALUES (
  'adrito', 'M_008', 170,92,TO_DATE('22/08/2022','dd/mm/yyyy'), 'Reduce Weight','Rafid Mustakim'
);

INSERT INTO MEMBER (
  USERNAME, MEM_ID, MEM_HEIGHT, MEM_WEIGHT, MEMBERSHIP_EXPIRY, EXPECTED_OUTCOME, TRAINER
)
  VALUES (
  'naiem', 'M_009', 171,62,TO_DATE('22/07/2022','dd/mm/yyyy'), 'Increase Weight','Shah Ishraq'
);

INSERT INTO MEMBER (
  USERNAME, MEM_ID, MEM_HEIGHT, MEM_WEIGHT, MEMBERSHIP_EXPIRY, EXPECTED_OUTCOME, TRAINER
)
  VALUES (
  'naima', 'M_010', 161,58,TO_DATE('22/07/2022','dd/mm/yyyy'), 'Increase Height','Mahmud Hasan'
);

INSERT INTO MEMBER (
  USERNAME, MEM_ID, MEM_HEIGHT, MEM_WEIGHT, MEMBERSHIP_EXPIRY, EXPECTED_OUTCOME, TRAINER
)
  VALUES (
  'megh', 'M_011', 166,71,TO_DATE('18/07/2022','dd/mm/yyyy'), 'Reduce Weight','Mahmud Hasan'
);






