INSERT INTO MESSAGE(
    MES_ID,RECIEVER_ID,SUBJECT,DESCRIPTION,SENDER_ID,S_DATE
)VALUES(
    per_mes_id_sq.NEXTVAL,26,'REPORTING ABOUT AN EQUIPMENT','THE DUMBLE HAS BEEN BROKEN. PLEASE CHECK AND TAKE NECESSARY ACTIONS.',2,SYSDATE
);

INSERT INTO MESSAGE(
    MES_ID,RECIEVER_ID,SUBJECT,DESCRIPTION,SENDER_ID,S_DATE
)VALUES(
    per_mes_id_sq.NEXTVAL,21,'ABOUT PROVIDING A DIET CHART','I HAVE GIVEN MY REASON TO REGISTER INTO THE GYM BUT STILL DID NOT GET
    ANY DIET CHART. PLEASE PROVIDE SOME GUIDELINES AND A DIET CHART FOR ME',3,SYSDATE
);

INSERT INTO MESSAGE(
    MES_ID,RECIEVER_ID,SUBJECT,DESCRIPTION,SENDER_ID,S_DATE
)VALUES(
    per_mes_id_sq.NEXTVAL,21,'IMPORTANT NOTICE!!!','DUE TO EID-UL-ADHA, THE GYM WILL BE CLOSED FOR 7 DAYS',4,SYSDATE
);

INSERT INTO MESSAGE(
    MES_ID,RECIEVER_ID,SUBJECT,DESCRIPTION,SENDER_ID,S_DATE
)VALUES(
    per_mes_id_sq.NEXTVAL,20,'NEW EXERCISE ROUTINE REQUIRED','I HAVE LOST MY EXERCISE LIST. CAN YOU PROVIDE ME A NEW ONE?',9,SYSDATE
);

INSERT INTO MESSAGE(
    MES_ID,RECIEVER_ID,SUBJECT,DESCRIPTION,SENDER_ID,S_DATE
)VALUES(
    per_mes_id_sq.NEXTVAL,14,'SPACE NEEDED','MEMBERS HAVE BEEN INCREASING DAY BY DAY INTO OUR GYM. IT HAS BEEN DIFFICULT TO FIT THEM ALL INTO OUR GYM. SO, NEW BRANCH NEEDED OR SPACE NEEDED TO FIT THEM ALL.',6,SYSDATE
);













INSERT INTO MESSAGE(
    MES_ID,RECIEVER_ID,SUBJECT,DESCRIPTION,SENDER_ID
)VALUES(
    per_mes_id_sq.NEXTVAL,9,'IN SHORT OF FUNDS FOR OUR GYM','OUR GYM NEEDS MORE FUNDS FOR RECUITING MORE TRAINERS FOR OUR MEMBERS',3
);

INSERT INTO MESSAGE(
    MES_ID,RECIEVER_ID,SUBJECT,DESCRIPTION,SENDER_ID
)VALUES(
    per_mes_id_sq.NEXTVAL,9,'IMPORTANT NOTICE!!!','DUE TO EID-UL-ADHA, THE GYM WILL BE CLOSED FOR 7 DAYS',21
);

INSERT INTO MESSAGE(
    MES_ID,RECIEVER_ID,SUBJECT,DESCRIPTION,SENDER_ID
)VALUES(
    per_mes_id_sq.NEXTVAL,9,'In need of more managers ','Our manager number needs to be increased to make our gym availabale 18 hours a day',5
);

INSERT INTO MESSAGE(
    MES_ID,RECIEVER_ID,SUBJECT,DESCRIPTION,SENDER_ID
)VALUES(
    per_mes_id_sq.NEXTVAL,9,'SPACE NEEDED','MEMBERS HAVE BEEN INCREASING DAY BY DAY INTO OUR GYM. IT HAS BEEN DIFFICULT TO FIT THEM ALL INTO OUR GYM. SO, NEW BRANCH NEEDED OR SPACE NEEDED TO FIT THEM ALL.',6
);
