INSERT INTO MESSAGE(
    MES_ID,RECIEVER_ID,SUBJECT,DESCRIPTION,USERNAME
)VALUES(
    01,26,'REPORTING ABOUT AN EQUIPMENT','THE DUMBLE HAS BEEN BROKEN. PLEASE CHECK AND TAKE NECESSARY ACTIONS.','megh'
);

INSERT INTO MESSAGE(
    MES_ID,RECIEVER_ID,SUBJECT,DESCRIPTION,USERNAME
)VALUES(
    02,21,'ABOUT PROVIDING A DIET CHART','I HAVE GIVEN MY REASON TO REGISTER INTO THE GYM BUT STILL DID NOT GET
    ANY DIET CHART. PLEASE PROVIDE SOME GUIDELINES AND A DIET CHART FOR ME','arafat'
);

INSERT INTO MESSAGE(
    MES_ID,RECIEVER_ID,SUBJECT,DESCRIPTION,USERNAME
)VALUES(
    03,21,'IMPORTANT NOTICE!!!','DUE TO EID-UL-ADHA, THE GYM WILL BE CLOSED FOR 7 DAYS','brownFalcon'
);

INSERT INTO MESSAGE(
    MES_ID,RECIEVER_ID,SUBJECT,DESCRIPTION,USERNAME
)VALUES(
    04,20,'NEW EXERCISE ROUTINE REQUIRED','I HAVE LOST MY EXERCISE LIST. CAN YOU PROVIDE ME A NEW ONE?','Ayon037'
);

INSERT INTO MESSAGE(
    MES_ID,RECIEVER_ID,SUBJECT,DESCRIPTION,USERNAME
)VALUES(
    05,14,'SPACE NEEDED','MEMBERS HAVE BEEN INCREASING DAY BY DAY INTO OUR GYM. IT HAS BEEN DIFFICULT TO FIT THEM ALL INTO OUR GYM. SO, NEW BRANCH NEEDED OR SPACE NEEDED TO FIT THEM ALL.','karim'
);

