INSERT INTO ROUTINE(
    USERNAME,EXE_ID,DAYS,FOLLOWED_SET
)VALUES(
    'afk999',01,03,30
);

INSERT INTO ROUTINE(
    USERNAME,EXE_ID,DAYS,FOLLOWED_SET
)VALUES(
    'Ayon037',02,03,30
);

INSERT INTO ROUTINE(
    USERNAME,EXE_ID,DAYS,FOLLOWED_SET
)VALUES(
    'hasnat',03,04,15
);


INSERT INTO ROUTINE(
    USERNAME,EXE_ID,DAYS,FOLLOWED_SET
)VALUES(
    'rashid',04,02,15
);

INSERT INTO ROUTINE(
    USERNAME,EXE_ID,DAYS,FOLLOWED_SET
)VALUES(
    'meher',04,03,30
);


INSERT INTO ROUTINE(
    USERNAME,EXE_ID,DAYS,FOLLOWED_SET
)VALUES(
    'rahat',01,03,30
);


INSERT INTO ROUTINE(
    USERNAME,EXE_ID,DAYS,FOLLOWED_SET
)VALUES(
    'arafat',04,04,20
);


INSERT INTO ROUTINE(
    USERNAME,EXE_ID,DAYS,FOLLOWED_SET
)VALUES(
    'adrito',05,03,30
);


INSERT INTO ROUTINE(
    USERNAME,EXE_ID,DAYS,FOLLOWED_SET
)VALUES(
    'naiem',03,05,15
);


INSERT INTO ROUTINE(
    USERNAME,EXE_ID,DAYS,FOLLOWED_SET
)VALUES(
    'naima',03,05,15
);

INSERT INTO ROUTINE(
    USERNAME,EXE_ID,DAYS,FOLLOWED_SET
)VALUES(
    'megh',03,05,20
);

INSERT INTO ROUTINE(
    USERNAME,EXE_ID,DAYS,FOLLOWED_SET
)VALUES(
    'ruposhi',02,06,35
);


INSERT INTO ROUTINE(
    USERNAME,EXE_ID,DAYS,FOLLOWED_SET
)VALUES(
    'pant',03,06,35
);